version: '3.7'

services:

  <app_name>:
    hostname: <app_name>
    image: <app_name>
    container_name: <app_name>
    restart: always
    build: .
    networks:
      card:
        ipv4_address: 172.21.0.3

networks:
  card:
    name: card
    ipam: 
      config:
        - subnet: 172.21.0.0/16
