version: "3.8"

services:

  fe:
    container_name: fe
    image: fe
    build: .
    ports:
      - 8000:80
    networks:
      card:
        ipv4_address: 172.21.0.5

networks:
  card:
    name: card
    ipam: 
      config:
        - subnet: 172.21.0.0/16
